version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: yolojaem-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis:/data

  timescaledb:
    image: timescale/timescaledb:2.16.1-pg16
    container_name: yolojaem-timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yolojaem
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/timescaledb:/var/lib/postgresql/data

networks:
  default:
    name: yolojaem-net

